---
- hosts: jenkins_server_01
  become: yes
  tasks:
    - name: Ensure pre-requisites exist
      import_role:
        name: ubuntu-add-sudoer

    - name: Install Java recommended in ansible-jenkins-role
      apt:
        name: openjdk-11-jre
        state: present
        update_cache: yes

    - name: Create ca and deploy self signed certificates
      vars:
        certs_fqdns:
          - '{{ domain }}'
      import_role:
        name: ansible-certificates-role
      when: deploy_self_signed_cert
