---
- hosts: all
  become: yes
  tasks:
    - name: Add jenkins user
      import_role:
        name: ubuntu-add-sudoer
      vars:
        username: jenkins
        user_comment: jenkins user
        sudoer: no
        passwordless_sudo: no

    - name: Install Java recommended in ansible-jenkins-role
      apt:
        name: openjdk-11-jre
        state: present
        update_cache: yes

    - name: Create ca and deploy self signed certificates
      vars:
        certs_fqdns:
          - '{{ fqdn }}'
      import_role:
        name: ansible-certificates-role
      when: deploy_self_signed_cert
